services:
  deneme-berkecan:
    build:
      dockerfile: Dockerfile
    container_name: browtop-arda
    pid: host # for getting the host's ps aux, it is not a good approach but a way to get the host's ps aux
    ports:
      - "1033:8765"
    tty: true
    volumes:
      - /var/run/utmp:/var/run/utmp:ro  # for getting the host's current users
      - /var/log/wtmp:/var/log/wtmp:ro  # for getting the host's last users
      - /var/log/syslog:/var/log/syslog # for getting the host's syslog
