services:
  monitor:
    build: .
    container_name: monitor_app
    ports:
      - "1022:8765"  
    environment:
      - PORT=8765
    volumes:
      - ./cert:/app/cert
    restart: unless-stopped
